derive Serialize and Deserialize for BoundsIterator (#149)
The crate does not compile with the `egui_persistence` feature because
`BoundsIterator` does not implement `Serialize` and `Deserialize`.

`BoundsIterator` is used by the `Metadata` struct which does derive both
traits.
```rs
#[cfg_attr(
    feature = "egui_persistence",
    derive(serde::Serialize, serde::Deserialize)
)]
#[derive(Clone, Debug)]
pub struct Metadata {
    /// Whether the frame is the first one
    pub first_frame: bool,
    /// Current zoom factor
    pub zoom: f32,
    /// Current pan offset
    pub pan: Vec2,
    /// Top left position of widget
    pub top_left: Pos2,

    /// State of bounds iteration
    bounds_iterator: BoundsIterator,
}
```

```
egui_graphs = { version = "0.17.0", features = ["egui_persistence", "serde"] }
```

The error:
```console
error[E0277]: the trait bound `BoundsIterator: Deserialize<'_>` is not satisfied
    --> /home/bruno/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui_graphs-0.17.0/src/metadata.rs:63:22
     |
63   |     bounds_iterator: BoundsIterator,
     |                      ^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `BoundsIterator`
     |
     = help: the following other types implement trait `Deserialize<'de>`:
               bool
               char
               isize
               i8
               i16
               i32
               i64
               i128
             and 297 others
note: required by a bound in `next_element`
```